### ISSUE TITLE
new images for i2c2oled

### ISSUE THREAD

**Issue by pplatoon** [venice1200/MiSTer_i2c2oled_Pictures#2]
Hi
I have created some images that are not available, how can they be uploaded? 

Thanks

**Comment by venice1200** [comment]
Open a pull request here is the easiest way.
Or drop them to the MiSTer Forums Thread and i will upload them.

**Comment by pplatoon** [comment]
> Open a pull request here is the easiest way. Or drop them to the MiSTer Forums Thread and i will upload them.

https://mega.nz/folder/6GR2DBaA#NVPbhOzalyd-9oNd9usRrQ

**Comment by venice1200** [comment]
I uploaded the Pictures. Many Thanks.

Please double check them at the pixviewer. 
https://venice1200.github.io/MiSTer_tty2oled_Pictures/

The Playstation Logo, **renamed to PSX_alt3**, looks strange.
Your Punisher Picture was **renamed to punisher_alt2** as we already have an Punisher Picture.

**Comment by venice1200** [comment]
I have corrected the PSX Picture by removing one Bit at the end of each line.
Looks OK now.

Cheers
